[package]
name = "ghui"
description = "Command line tools for working with GitHub projects"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
tui = ["dep:ratatui", "dep:crossterm"]

[dependencies]
clap = { workspace = true }
crossterm = { workspace = true, optional = true }
ratatui = { workspace = true, optional = true }
