[package]
name = "ghui"
description = "Command line tools for working with GitHub projects"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gh-ghui"
path = "src/main.rs"

[features]
default = ["tui"]
tui = ["dep:ratatui", "dep:crossterm", "dep:tui-markdown"]

[dependencies]
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
crossterm = { workspace = true, optional = true }
ratatui = { workspace = true, optional = true }
tui-markdown = { workspace = true, optional = true }

[dev-dependencies]
assert_cmd = "2"
httpmock = "0.8"
predicates = "3"


